import './globals.css'
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: "300" })

export const metadata: Metadata = {
  title: 'ImageLite',
  description: 'Generated by create next app',
}

export default ({
                  children,
                }: {
  children: React.ReactNode
}) => (
    <html lang="pt-br">
    <body className={roboto.className}>{children}</body>
    </html>
)
